### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by here4thefun** [xKynn/PokecordCatcher#1]
Thanks for the auto catcher. It is amazing. Anyway, here is something I noticed:
![help](https://user-images.githubusercontent.com/37678516/37806591-cf89e4b0-2e7b-11e8-932f-673994507d7f.JPG)

Anything I can do to fix this?

**Comment by xKynn** [comment]
I'll look into it

**Comment by rexosorous** [comment]
it has to do with lines 38-39. for some reason you're popping pokemon from the priority list and then immediately afterward, you're checking to see if that pokemon is in the priority list. removing both lines 38 and 39 fixes this issue.

**Comment by xKynn** [comment]
@rexosorous id appreciate if you could submit a PR, ill be out for a couple hours now, but i can fix after.
