### ISSUE TITLE
i cant run it its showing this

### ISSUE THREAD

**Issue by vinay2674** [xKynn/PokecordCatcher#10]
C:\Users\VINAY\Desktop\b\PokecordCatcher-0.2.4>py -3 launcher.py
'py' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\VINAY\Desktop\b\PokecordCatcher-0.2.4>timeout -1

Press any key to continue ...

after clicking any key its closing

**Comment by Hyperclaw79** [comment]
replace `py -3` with `python` and it will work. 👍

**Comment by vinay2674** [comment]
means i am new in this how to and what to replace

**Comment by Hyperclaw79** [comment]
@vinay2674 replace it in your `run.bat`
