### ISSUE TITLE
Delay not working

### ISSUE THREAD

**Issue by SeikoEMP** [xKynn/PokecordCatcher#13]
Changed the delay and it still catches instantly

**Comment by vinay2674** [comment]
change delay to what can u give me full script i will only write names of
pokes that i want

**Comment by Hyperclaw79** [comment]
Are you sure about this? Since this version doesn't use `async-with typing()` context manager, it looks like the reply is instant and not like it is being typed. You might wanna check my extension if you want more advanced features.

**Comment by Zwen13579** [comment]
Same for me It catches insta. idk why i chanched the times it still dosnt work

**Comment by xKynn** [comment]
If you're not getting delay on a priority pokemon then you might not have delay_on_priority set to true

**Comment by xKynn** [comment]
Could one of you guys with delay not working post your config here? Post it without your token inside it.

**Comment by SeikoEMP** [comment]
Sure! once I get back home from work I'll post mine

**Comment by ThaBlazee** [comment]
@xKynn Any way to contact you off github? i want to discuss something. my discrord is blaze#1679

**Comment by SeikoEMP** [comment]
Looks like with the update that you released a couple days back helped with my delay issue cause it works now
