### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by ThaBlazee** [xKynn/PokecordCatcher#14]
The priority isn't working, when i set the catch rate to 100% and set to priority only as true, it still catches all pokemon. but i thought to set a workaround by setting catchrate to 0 and ive been running the program for a couple of days, none of the pokemon in the priority list are being caught, even if i place normal ones, idk they don't even show as skipped.

**Comment by xKynn** [comment]
I'll test this and a couple more things in about 2 hours from now, thanks

**Comment by ThaBlazee** [comment]
bump

**Comment by xKynn** [comment]
Fixed in #15
