### ISSUE TITLE
SyntaxError when running launcher.py

### ISSUE THREAD

**Issue by Virg099** [xKynn/PokecordCatcher#19]
So I have added the token and everything and setup the config.json, however when I run the launcher.py, i get this error: 
V-Pro:PokecordCatcher-master User$ python -3 launcher.py
```py
Traceback (most recent call last):
  File "launcher.py", line 2, in <module>
    from pokecordcatcher import Poke
  File "/Users/User/Downloads/PokecordCatcher-master/pokecordcatcher.py", line 11
    def __init__(self, config_path: str, *args, **kwargs):
                                  ^
SyntaxError: invalid syntax
```
Am I doing something wrong? Btw I'm using a mac.

**Comment by Virg099** [comment]
there are two "_" lines before and after the bolded "init"

**Comment by Hyperclaw79** [comment]
looks like an outdated version of Python. Update to 3.6 and it will work. Reopen if it doesn't get resolved.

**Comment by Virg099** [comment]
Just updated, still the same error, python 3.6

**Comment by Virg099** [comment]
Sorry, I didn't know how to re-open

**Comment by Virg099** [comment]
So any updates?

**Comment by Hyperclaw79** [comment]
A local issue as seen in https://github.com/Hyperclaw79/PokeBall-SelfBot/issues/13.
Closing it till sufficient info is provided.
