### ISSUE TITLE
Pokemon names broken

### ISSUE THREAD

**Issue by NotchWith** [xKynn/PokecordCatcher#2]
It seems the bot pull the chat names from the URL link of the pictures. That no longer works as they seemed to have been randomized. 

also never got the priority only work right but blacklist did.  

Awesome bot none the less

**Comment by Decrupt** [comment]
Yea, the url has changed. Before they used like a Pokemon Wiki but you could just check the URL to see which pokemon it was. Now they have changed that so the bot ain't workin'

**Comment by xKynn** [comment]
I've added a workaround to this, it works again now
