### ISSUE TITLE
Still The Same Syntax Error

### ISSUE THREAD

**Issue by Virg099** [xKynn/PokecordCatcher#20]
Already updated to 3.6, still doesn't work. 

V-Pro:~ User$ python --version
Python 3.6.5
V-Pro:~ User$ cd '/Users/User/Downloads/PokecordCatcher-master/' && '/usr/bin/pythonw' -i  '/Users/User/Downloads/PokecordCatcher-master/launcher.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/User/Downloads/PokecordCatcher-master/launcher.py", line 2, in <module>
    from pokecordcatcher import Poke
  File "/Users/User/Downloads/PokecordCatcher-master/pokecordcatcher.py", line 11
    def __init__(self, config_path: str, *args, **kwargs):
                                  ^
SyntaxError: invalid syntax
>>>

**Comment by Hyperclaw79** [comment]
Let's use a single issue to keep track of this. You can always reopen a closed issue if you're the original poster.

So, back to https://github.com/xKynn/PokecordCatcher/issues/19.
