### ISSUE TITLE
not catching pokemon

### ISSUE THREAD

**Issue by weirdmario** [xKynn/PokecordCatcher#22]
I have the PokecordCatcher running and it is not catching Pokemon, regardless of catch rate being 90 or 100.

**Comment by wdfghj** [comment]
Hey, you have to say P^autocatcher on
In your chat, then it Will catch pokemon automaticly

**Comment by weirdmario** [comment]
Still not working.

**Comment by Hyperclaw79** [comment]
Lmfao no, that's for my bot.

**Comment by weirdmario** [comment]
oh, well somebody needs to make mine work

**Comment by weirdmario** [comment]
i figured it out, needed to add more channel numbers to the config file
