### ISSUE TITLE
Deployment issue - Token syntax in config.json

### ISSUE THREAD

**Issue by micky0singh** [xKynn/PokecordCatcher#23]
Hey,
i downloaded latest release
and edit config.json like this
{
  "token": ""xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"",
  "priority": ["Groudon", "Rayquaza", "Shaymin", "Marshadow", "Xerneas", "Solgaleo", "Lunala", "Magikarp"],
  "catch_rate": 100,
  "delay": 2,
  "delay_on_priority": true,
  "priority_only": false,
  "avoid_list": [],
  "whitelist_channels": [430820639776178176],
  "blacklist_channels": [382316968394620938],
  "verbose": false
}
i run launcher.exe it opens and close
and when a pokemon spawned it's not catching pokemon automatically
i have not banned i still can access every pokecord command and catch them by p!catch 
my question is why it's not catching pokemon automatically.
please help me

**Comment by Hyperclaw79** [comment]
Please edit your question to censor your token. You've just exposed your account to the world.

**Comment by micky0singh** [comment]
so if i add only this ” ” it will run right also 
launcher automatically opens and closes is it okay and i know m asking for too much help can u do one more favor from where should i use it 
desktop or web

**Comment by Hyperclaw79** [comment]
No no, I mean only the `token` instead of `"token"`.
i.e.,
`"token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",`
instead of:
`"token": ""xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"",`

**Comment by Hyperclaw79** [comment]
No response from the OP.
Assuming the problem has been solved.
Closing this.
