### ISSUE TITLE
Aiohttp HttpWriter error

### ISSUE THREAD

**Issue by webcarchili** [xKynn/PokecordCatcher#27]
I got an error?
![helps](https://user-images.githubusercontent.com/38995422/39658586-643d8222-4fcb-11e8-8978-015c4cf55ecd.PNG)

**Comment by Hyperclaw79** [comment]
Similar issue found at my repo:
https://github.com/Hyperclaw79/PokeBall-SelfBot/issues/14

**Comment by schan3Ed** [comment]
Try upgrade your aiohttp module
```
pip install --upgrade aiohttp
```

**Comment by bueluke** [comment]
if your issue has been solved pls close this issue!

**Comment by Hyperclaw79** [comment]
Fixed in https://github.com/xKynn/PokecordCatcher/pull/67.
