### ISSUE TITLE
Error catch Hariyama

### ISSUE THREAD

**Issue by Wolwaree** [xKynn/PokecordCatcher#28]
With the latest version of pokecatcher an error appears when it try to catch Hariyama
it would be the hosting of the pokemon image which is apparently imgur (not pokecord.com)
Link of Hariyama image : https://i.imgur.com/RGJszWM.png

![errorhariyama](https://user-images.githubusercontent.com/39082832/39747078-8c3bb7ce-52ac-11e8-96c1-7b4847fd9b9d.png)

**Comment by Hyperclaw79** [comment]
Fixed in https://github.com/xKynn/PokecordCatcher/pull/29.
