### ISSUE TITLE
Help with an error.

### ISSUE THREAD

**Issue by JoseDGomez** [xKynn/PokecordCatcher#3]
The selfbot works good, but sometimes it sends this 'error' or 'advice', please help.

Thank you for the selfbot bro.
![screenshot_1](https://user-images.githubusercontent.com/23449209/38566885-1a930762-3ce5-11e8-88e7-d973af9f3698.jpg)

**Comment by xKynn** [comment]
These have all been fixed, together with new checking methods and instantaneous speeds, update please, thanks!

**Comment by JoseDGomez** [comment]
Thank you so much <3
