### ISSUE TITLE
PokeCord Image Name Change Issue

### ISSUE THREAD

**Issue by bueluke** [xKynn/PokecordCatcher#33]
ERROR IN RUN.BAT . i run the script everything is fine a pokemon appears account doesnt catch it error pops up in console 

![](https://cdn.discordapp.com/attachments/443952125538729984/444593799126056971/unknown.png)

please reply to me asap

**Comment by Hyperclaw79** [comment]
PokeCord's latest update changed the image urls again, totally breaking the autocatcher. 
A solution is on its way. Please stay patient.

**Comment by The-Real-Ketchum-Dev** [comment]
yup they updated the bot to break the autocatch

**Comment by bueluke** [comment]
wdym?? who updated what @The-Real-Ketchum-Dev @Hyperclaw79 

msg me on discord @Hyperclaw79 i tried adding u but no results Captain Luke #0069

**Comment by Skylicker** [comment]
Can you add, release of trash, same pokemons?

**Comment by xKynn** [comment]
Refer to #34
