### ISSUE TITLE
PokecordSpawn keyerror

### ISSUE THREAD

**Issue by Kagine** [xKynn/PokecordCatcher#34]
So I've been using the bot [which is helpful, I appreciate it] but today I stumbled across this problem...

"Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 223, in _run_event
  File "C:\Users\asus\Desktop\PokecordCatcher-master\pokecordcatcher.py", line 45, in on_message
    name = self.pokeref[emb.image.url.split('/')[-1].split('.')[0]]
KeyError: 'PokecordSpawn'

Is there a workaround to fix this? it came out of the sudden - reinstalling doesn't seem to work.

**Comment by The-Real-Ketchum-Dev** [comment]
it was an update on pokecord they are working on it

**Comment by Kagine** [comment]
Oh really? Got me panicked for a moment. Guess we had to wait till they're fixed it?

**Comment by bueluke** [comment]
go to #33 @Kagine you'll see updates there

**Comment by The-Real-Ketchum-Dev** [comment]
yeah

**Comment by xKynn** [comment]
Hi, working on restoring to working conditions, average time taken to find pokemon from image is now 1.36 seconds which still seems pretty good

**Comment by Kagine** [comment]
@bueluke Okay.

@xKynn Good luck with the restoration, really.

**Comment by bueluke** [comment]
@xKynn hey man i just scripted a code that should "in theory" help with users not getting banned for botting contact me on discord for the script Captain Luke#0069

**Comment by xKynn** [comment]
Update is up, download the new release and let me know if you find any problems, thanks!
