### ISSUE TITLE
Not An ISSUE. Feedback

### ISSUE THREAD

**Issue by The-Real-Ketchum-Dev** [xKynn/PokecordCatcher#37]
So far seems to be working correctly. Been running for about 10ish minutes and is catching like planned

**Comment by Error404Again** [comment]
![image](https://user-images.githubusercontent.com/39204379/39950556-7e9b7270-55b4-11e8-9d61-85bf03328574.png)


These keep showing up

**Comment by xKynn** [comment]
Download the latest release again please, all issues should be fixed now

**Comment by The-Real-Ketchum-Dev** [comment]
it did that 2 times for me and then stopped

**Comment by xKynn** [comment]
i can't imagine any reason for more keyerrors but if you do get that can you find out what pokemon name it is and post it here with the image link?

**Comment by Error404Again** [comment]
![image](https://user-images.githubusercontent.com/39204379/39951116-7eee3e9c-55b9-11e8-9cca-00235c268efc.png)

;-;

**Comment by bueluke** [comment]
bot owners are not online atm! please be patient until they can fix this!

**Comment by xKynn** [comment]
Update to latest release
