### ISSUE TITLE
Some Pokemon errors that I've seen

### ISSUE THREAD

**Issue by Kagine** [xKynn/PokecordCatcher#39]
# This topic is solely for the list of Pokemon with faulted codes, and also on the bot progress after being used by me.

## EDIT on 1:09 AM 13/5/2018 = I clearly had seen that the bot does not capture any of my priority list Pokemon [such as the starters] so I had to manually catch them.

**Comment by Kagine** [comment]
Listing another. I noticed this one shows up when a Snubbull appeared.

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 223, in _run_event
  File "C:\Users\asus\Desktop\PokecordCatcher-master\pokecordcatcher.py", line 54, in on_message
    name = await self.match(emb.image.url)
  File "C:\Users\asus\Desktop\PokecordCatcher-master\pokecordcatcher.py", line 27, in match
    return self.poke[m]
KeyError: '6d2a77f856d23be548f0f5038f1d3d6e'

**Comment by Kagine** [comment]
@xKynn  Alright.

**Comment by etch286** [comment]
for me still same error appearing with latest release

**Comment by Kagine** [comment]
Well it wasn't updated. For now stopped hunting since it doesn't seem to catch anything for me by now.

**Comment by Kagine** [comment]
I'm keeping the post updated to find more spawn errors.

**Comment by Xenchrea** [comment]
Wingull 

![image](https://user-images.githubusercontent.com/39220538/39959063-4e31b7ca-5636-11e8-8270-1b414689d236.png)

**Comment by Kagine** [comment]
@Xenchrea I added that to the list too. Thanks.

**Comment by xKynn** [comment]
New update is up, all pokemons have been rehashed, total count came up to 807 so i'm hoping the hashes are accurate

**Comment by Kagine** [comment]
@xKynn  Alright, testing that now.
