### ISSUE TITLE
Tester

### ISSUE THREAD

**Issue by The-Real-Ketchum-Dev** [xKynn/PokecordCatcher#41]
If you guys are looking for testers you can find me on discord ༒TᴀͪsͤʜᴋᴇᴛᴄʜͬᴜͤᴍͣL ™༒#8472

**Comment by Hyperclaw79** [comment]
Thanks for the enthusiasm. Every user is allowed to test it locally. All they gotta do is, post the invalid key along with the pokemon.
Either way, @xKynn is working on an update atm. You can test it after it is released.
