### ISSUE TITLE
I need help setting up the bot

### ISSUE THREAD

**Issue by Grovylethethief** [xKynn/PokecordCatcher#42]
I have downloaded all the main stuff from the PokecordCatcher-1.0.0.zip file but i didn't download the tar.gz as it seemed unnecessary. I followed the guide; got my Token and edited poke.json. Then it says, load up launcher.exe... i don't have that specific file but launcher.py and i'm aware py is a python file which made me download python 3.6.5. And it includes python but also pythonw which i don't know the difference. Also, when i try to open launcher.py or PokecordCatcher.py, python crashes and pythonw doesn't even want to load up. When i try to open Setup.bat or Run.bat, it says that .py is an unsupported prefix... i don't know if i'm being blind or have the wrong files. If it matters, i am running windows 8.1 and am on a laptop. i followed the README.md but don't understand the launcher.exe thing. I am stumped so a bit of advice or help would be greatly appreciated!!

**Comment by bueluke** [comment]
message me on discord and ill help u @ Captain Luke #0069
