### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by sancturez** [xKynn/PokecordCatcher#46]
i clicked on run and it said something about the py can someone help? like how to set up the bot

**Comment by bueluke** [comment]
did it say something about "py is not recofnized as a internal or external command. that means u either have to download python which can be downloaded here https://www.python.org/downloads/ be sure to get the 3.6.5 version.

**Comment by sancturez** [comment]
thanks i got it now

**Comment by bueluke** [comment]
glad to assist :D
