### ISSUE TITLE
Problem timeout

### ISSUE THREAD

**Issue by Wolwaree** [xKynn/PokecordCatcher#48]
When i launch run.bat with the latest version (1.0.0 and tested with source code and release) :
![capture d ecran 228](https://user-images.githubusercontent.com/39082832/39971091-e80c89a0-56f5-11e8-812e-6d7e2856337c.png)

**Comment by bueluke** [comment]
did u add anything to the script/code? i have not seen this error before so i cant help u with this. i would suggest deleting the files and reinstalling them

**Comment by Wolwaree** [comment]
i explain : on avoid list the name of pokemon that begin with a "maj" are captured , i tested with min in begin but it's not work (and also in the poke.json the names of pokemon begin with a "min") , so i tested t oresolve this but this error appeared , the real problem is the avoid list who doesn't work

**Comment by xKynn** [comment]
Either your config or poke json is incorrectly formatted, I can't really help you with edits you've made yourself with insufficient info

**Comment by Wolwaree** [comment]
![capture d ecran 230](https://user-images.githubusercontent.com/39082832/40011439-20c6b7b8-57a8-11e8-9819-4a9dbbed31d8.png)
the avoid list in config.json not work

**Comment by bueluke** [comment]
bruh u dont want any pokemons huh 😂

**Comment by bueluke** [comment]
ohh gotcha

**Comment by xKynn** [comment]
Your config is incorrectly formatted, 
https://jsonlint.com/
paste the whole thing there and find out the error

**Comment by Wolwaree** [comment]
It's valid i didn't change the config since 0.2.5 there are a problem with 1.0.0 :/

**Comment by Wolwaree** [comment]
i think that the error is due to poke.json , before the 1.0.0 before that the names started with a capital letter , now it's begin with lower case

**Comment by Wolwaree** [comment]
it's work now , Thanks for the fix <3
