### ISSUE TITLE
Priority problem

### ISSUE THREAD

**Issue by Kagine** [xKynn/PokecordCatcher#49]
So I downloaded the latest files... but it seems that none of my priority pokemon were caught. [Say I had Trapinch on Priority but it won't respond]

![image](https://user-images.githubusercontent.com/39203467/40040038-3a3b45e4-584b-11e8-82b5-b3b92eb5e1b0.png)

I had placed in the current token, and if I deleted the whole priority list, it seems to capture anything that shows up normally.

**Comment by erackson** [comment]
Try setting priority_only: true

**Comment by Kagine** [comment]
@erackson I did that, it still didn't caught them.

**Comment by bueluke** [comment]
did u download the 1.0.1?

**Comment by Kagine** [comment]
@bueluke I found out the source. It turns out it is no longer accepting pokemon names that are written in caps at the start [say, "Groudon". I had to write "groudon" instead.] I ended up decapitalizing all of them and now it is working.

**Comment by bueluke** [comment]
allrighty sounds good. please close the issue. besure to make a new issue if theres any more problems :D

**Comment by xKynn** [comment]
I fixed exactly this in 1.0.1 do make sure you're on latest, and if you are
I'll look into the problem
