### ISSUE TITLE
Incorrect failure report in console

### ISSUE THREAD

**Issue by UltraNecrozma** [xKynn/PokecordCatcher#50]
In the console, PokecordCatcher is reporting a lot of failure, while, when you check the discord feed, there is no failure, all pokemons are perfectly catched and the only problem is maybe that Pokecord is very slow and takes a long time to validate the catch. So maybe the time out before declaring the catch is a failure is too short.

**Comment by bueluke** [comment]
is it saying"failed to catch (pokemon) when it did catch? if so that is a harmless error its just that the pokecord bot is taking a while to respond that u caught it. hope that helps

**Comment by xKynn** [comment]
There's a problem with pokecord where it queues up messages and doesnt
actually send tilo it has 2 in the queue, so you actually can wait forever
and it won't reply, i can look for other ways to validate the catch as well

**Comment by UltraNecrozma** [comment]
ok, I read they were working on it and are now stuck on Discord limit rates at peak hours, waiting on a reply by discord team about this.
Maybe simply check when a new one spawn (you already detect that) that the previous one has been caugh in between.
So split the log lines into : 
_ Trying to catch XXXXX
then either
_ Caugh XXXXX (when you detect the message in your timer or when you try to catch next one)
or 
_ Failed catching XXXXX (when you try to catch next one and there is no catch message for previous one)

Do you think that would be possible ?

**Comment by xKynn** [comment]
I'm going to check what the very next message after spawn is, so if anyone else actually puts a message before you it should technically be a fail, and if you're the first its successful

**Comment by UltraNecrozma** [comment]
not sure about that, even when not spamming or boting, you often have one or two normal chat messages between the spawn and the first .catch wich migh event be a wrong one ...

**Comment by xKynn** [comment]
It goes without saying that it would check if its a catch attempt and if
it's correct.

>

**Comment by xKynn** [comment]
I remember adding a fix for this in the code but I've never tested it

**Comment by UltraNecrozma** [comment]
Seems to me it's working perfectly well now, outside of the occasional server connexion crash (probably when Discord stops responding) everything else if working fine ;)

I'm closing the issue, thanks for the fix !
