### ISSUE TITLE
Nidoran female/male 

### ISSUE THREAD

**Issue by The-Real-Ketchum-Dev** [xKynn/PokecordCatcher#52]
Wont catch a nidoran female/male because of the symbol on the end

**Comment by bueluke** [comment]
sorry for the inconvenience , there is a new update out for the bot here ----> https://github.com/xKynn/PokecordCatcher/releases/tag/1.0.1 should fix the problem :D , any more issues pls reply to me.

**Comment by bueluke** [comment]
in your files there is a file named "poke.json" right click it and edit it. delete everything from it and paste the code from this https://gist.github.com/bueluke/88f52abb0b091baadcb658b1a251b04f into the poke.json and it will fix the gender issue.

**Comment by xKynn** [comment]
has been fixed in 1.0.1
