### ISSUE TITLE
I need help learning to set up..

### ISSUE THREAD

**Issue by DrineRera** [xKynn/PokecordCatcher#54]
I already have put everything needed in config.json
![image](https://user-images.githubusercontent.com/39415112/40247562-7f03280e-5ad5-11e8-98c4-ffb775ab788b.png)
This is currently what the file looks like.

**Comment by xKynn** [comment]
Go to https://github.com/xKynn/PokecordCatcher/releases , download the latest release, extract, edit config  and run launcher.exe, please read the readme, it has all the instructions for this, reopen if you have problems with the release.

**Comment by bueluke** [comment]
go to cmd and type this in pip install --upgrade aiohttp if that doesnt work be sure to msg me on discord and ill help out. Captain Luke #0069

**Comment by DrineRera** [comment]
Sent an invite on discord. And It's still not working for me. "pip" is not an internal or external commnd
