### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by aforawesome** [xKynn/PokecordCatcher#56]
Here is the screenshot
![sdfds](https://user-images.githubusercontent.com/35620345/40308634-76e0427c-5d39-11e8-9a4c-906355c4d758.PNG)

**Comment by bueluke** [comment]
setup.bat closes on its own. "it doesnt work run.bat" im not sure i understand! , msg me on discord and ill try to help best as i can. Captain Luke #0069

**Comment by Hyperclaw79** [comment]
@aforawesome Do close this if it has been resolved.
