### ISSUE TITLE
phyton setup.phy egg_info failed with error code 1

### ISSUE THREAD

**Issue by Lenqa** [xKynn/PokecordCatcher#61]
![screenshot_4](https://user-images.githubusercontent.com/39681569/40591353-efb18d66-620f-11e8-8ef3-97145f9e1b93.png)

Setup not working. :/

**Comment by bueluke** [comment]
thats supposed to happen i get that all the time its just a harmless error that everyone has

**Comment by xKynn** [comment]
If you're on windows please go through the readme again, clearly says you
should use a 'release'

**Comment by Lenqa** [comment]
The Links are not working.

**Comment by Lenqa** [comment]
Working! Thanks :)
