### ISSUE TITLE
Author ID's are in integers, not strings

### ISSUE THREAD

**Issue by JBWalrider** [xKynn/PokecordCatcher#62]
An issue is causing the bot not to recognize any messages as being sent by the bot.  The code in pokecordcatcher.py compares the author ID to an integer:
`if message.author.id == 365975655608745985 and message.embeds:`

It should compare to a string:
`if message.author.id == "365975655608745985" and message.embeds:`

**Comment by xKynn** [comment]
Shouldn't be a problem because the dependency is discord rewrite which uses
ints for IDs

**Comment by Hyperclaw79** [comment]
Or `Snowflakes` as they call it.
Either way, the bot sometimes lags and that is the reason why it doesn't detect messages.
