### ISSUE TITLE
Autocatcher not working.

### ISSUE THREAD

**Issue by ErickZMaster** [xKynn/PokecordCatcher#66]
Do nothing
![donothing](https://user-images.githubusercontent.com/20909916/40640753-03cf630e-62dd-11e8-856e-37d7f69fcc78.PNG)

**Comment by ErickZMaster** [comment]
![error](https://user-images.githubusercontent.com/20909916/40636426-77b0ed4c-62c4-11e8-9577-6d0e1aa4b0e0.PNG)

**Comment by Hyperclaw79** [comment]
uhm... post the screenshot of the error instead. The bot looks like it is running fine.

**Comment by ErickZMaster** [comment]
dosent catch

**Comment by ErickZMaster** [comment]
"token": "MjI0NDA8MjAwNjA0MzF2Njcy.DejJzg.m5P9GlTXjVvujFeHikmIWVOIL-5",
  "priority": [],
  "catch_rate": 100,
  "delay": 2,
  "delay_on_priority": true,
  "priority_only": false,
  "avoid_list": [],
  "whitelist_channels": [449413225931341837,257571659437834240],
  "blacklist_channels": [],
  "verbose": true

**Comment by xKynn** [comment]
this config looks fine, did you restart the bot after editing the config?

**Comment by xKynn** [comment]
Also hoping you know that whitelist means it will only catch in the channels you've added there

**Comment by ErickZMaster** [comment]
Yea i add the correct chanels

**Comment by ErickZMaster** [comment]
and i restart the bot :(

**Comment by Hyperclaw79** [comment]
@xKynn You edited his code to censor his token, but he actually had an extra `"` in there.

**Comment by ErickZMaster** [comment]
{
  "token": "",
  "priority": [],
  "catch_rate": 100,
  "delay": 2,
  "delay_on_priority": true,
  "priority_only": false,
  "avoid_list": [],
  "whitelist_channels": [449413225931341837,257571659437834240],
  "blacklist_channels": [],
  "verbose": true
}

**Comment by bueluke** [comment]
@ErickZMaster did u ever get this issue resolved?

**Comment by bueluke** [comment]
if you still need help open another issue
