### ISSUE TITLE
Bot Wont Catch?

### ISSUE THREAD

**Issue by daddyDinosaur** [xKynn/PokecordCatcher#69]
Iv loaded up the bot and it wont catch anything for me.
http://prntscr.com/jolkpl

**Comment by daddyDinosaur** [comment]
no, want screenshot?

**Comment by xKynn** [comment]
As long as the channels are the ones where you are testing, I've got a
couple reports of pokemon not being caught ill take a look when i can

**Comment by bueluke** [comment]
Problem fixed in discord (issue was resolved after deleting the files and reinstalling them
