### ISSUE TITLE
Alert on bot

### ISSUE THREAD

**Issue by StickySenju** [xKynn/PokecordCatcher#7]
the bot, send an alert that i don't know what it means, help me if u can please.
Thank you.
![screenshot_2](https://user-images.githubusercontent.com/38285095/38615429-e9722d00-3d90-11e8-8070-8d6debb26ca3.jpg)

**Comment by xKynn** [comment]
I'll have it ignore some of the harmless errors soon, but yeah no need to worry it's a harmless problem

**Comment by StickySenju** [comment]
i post this because it start to happen when i use the priority for some pokemons and i was confuses, but thanks
