### ISSUE TITLE
Excuse my rudeness for opening a new issue,

### ISSUE THREAD

**Issue by JBWalrider** [xKynn/PokecordCatcher#70]
but your comment on issue #63 was uncalled for.  Why did you assume that I hadn't even seen an error pop up?  Stop being so negative about it; I was simply trying to help and point out some error I received.  I have since fixed it such that it worked on my machine, having to change at least 10-15 lines of code here and there.  

If you don't care enough as a developer to listen to other people's concerns without pretending that we're all dumbasses that don't know how to operate a computer, then maybe I could have shown you some screenshots and your code could have been improved.  Rather, you decided to become defensive and deny the fact that your code could have possibly had a slight chance of not working on a client's machine.  

Please try to give a little more credit to your users because we all just want to catch pokemon, right? :)

**Comment by JBWalrider** [comment]
:omegalul: sorry about that im a bit drunk, but im at least semi-right, so try to read it before ya delete it, thanks dude

**Comment by xKynn** [comment]
Wew, I too usually reply to issues on here as soon as i wake up, about the
only time i even work on this thing. Also I'm quick to disregard stuff for
this project mostly only because 90% of the userbase is very very young
people, and sure I'll take a look at it I just can't find the time to work
on this lately.

**Comment by xKynn** [comment]
Unless d.py rewrite changed embed objects to dicts for some reason, 
`name = await self.match(emb.image.url.split('?')[0])`
Is the correct way to access an embed's image url, this was the reason i had closed it earlier, do let me know if you certainly know that d.py had this changed recently

**Comment by bueluke** [comment]
*shook*
