### ISSUE TITLE
The cmd wont work

### ISSUE THREAD

**Issue by Alpha1229** [xKynn/PokecordCatcher#71]

**Comment by xKynn** [comment]
Hey, you seem to not be using a packaged release that makes setting the bot up much easier. on the main project page you should see a releases tab on the top right side, download the latest one and follow the readme again. If you have any more problems with that I'll be happy to help

**Comment by Alpha1229** [comment]
ok now it works 
i have a question though 
how do i change the server 
for some reason, the bot only collects the pokemon in one server and not the rest

**Comment by bueluke** [comment]
"cmd wont work" 😂 that made me bust out laughing
