### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by JoKillerPT** [xKynn/PokecordCatcher#73]
when i click setup the cmd and close

**Comment by bueluke** [comment]
its supposed to automatically close 😂 
after u run the setup and go through the whole adding whitelist channels and adding tokens run `run.bat` if cmd opens and says logged in and brings up a menu type message you're all good

**Comment by JoKillerPT** [comment]
when i open run get that https://gyazo.com/cdb3254739e062fbcc7f95424621f307

**Comment by JoKillerPT** [comment]
i instlled python  but get that error https://gyazo.com/03bc6a3a1fec401650e4e519d84eec92
and i try install aiohttp and get error https://gyazo.com/2a388c0875193d27eea1ac85e0d4f515

**Comment by bueluke** [comment]
what version of python did u install? and did u setup python right? did u click on pip and set path

**Comment by JoKillerPT** [comment]
python 3.6.5

**Comment by bueluke** [comment]
ok did u add python to your path

**Comment by JoKillerPT** [comment]
no but i unistall and reinstall and select pythaon path and get that https://gyazo.com/78b3501b0b941c854545d7db15ca6489

**Comment by bueluke** [comment]
ok do me a favor uninstall python and when it brings up the popup to modify,uninstall or repair click modify and make sure everything is checked on the optional features thing pip,documentation,td.tk,oython test suite, then hit next (advanced options will show) make sure- (associate files with python , create shortcuts , and add python to environment variables is checked then hit that install button

**Comment by JoKillerPT** [comment]
all done but now get more red errors 
https://gyazo.com/11dd8de3f5facfaa28ed19c428afb6f1
https://gyazo.com/782ef4e11b78dc7e7368197e2fa7a0d4

**Comment by bueluke** [comment]
here msg me on discord so i can assist u further @Captain Luke#0069

**Comment by JoKillerPT** [comment]
dont find any nick name on discord add @joao#9127

**Comment by bueluke** [comment]
https://discord.gg/k2AFKz i couldnt find it so just join this

**Comment by bueluke** [comment]
Problem was fixed !went to discord couldn't figure out what was happening. updated some files and now everything is working now :D
