### ISSUE TITLE
I cant launch the bot

### ISSUE THREAD

**Issue by skondar** [xKynn/PokecordCatcher#75]
Im done iwth the  json config but inside the folder theirs programs 1 says LAUNCHER and the other one says RUN if i click run this is what i get 

C:\Users\Användare\Downloads\BallardAppCraftery.CraftyFileViewer_epyrqhfctk40t!App\PokecordCatcher-master>py -3 launcher.py
'py' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Användare\Downloads\BallardAppCraftery.CraftyFileViewer_epyrqhfctk40t!App\PokecordCatcher-master>timeout -1

Press any key to continue ... 

but when i click a key nothing happens
 and when i click launcher i get this in my notes program 

import sys
from pokecordcatcher import Poke

if __name__ == "__main__":
    try:
        config_path = sys.argv[1]
    except:
        config_path = 'config.json'

    bot = Poke(config_path)
    bot.run()

what am i supposed to do to launch the bot?

**Comment by bueluke** [comment]
ok , do u have python installed? open cmd type python if it comes up with something then u have it if not then install python 3.6.5  https://www.python.org/downloads/ , please refer to #46 #10

**Comment by skondar** [comment]
C:\Users\Användare\Downloads\BallardAppCraftery.CraftyFileViewer_epyrqhfctk40t!App\PokecordCatcher-master>py -3 launcher.py
Traceback (most recent call last):
  File "launcher.py", line 2, in <module>
    from pokecordcatcher import Poke
  File "C:\Users\Användare\Downloads\BallardAppCraftery.CraftyFileViewer_epyrqhfctk40t!App\PokecordCatcher-master\pokecordcatcher.py", line 2, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

C:\Users\Användare\Downloads\BallardAppCraftery.CraftyFileViewer_epyrqhfctk40t!App\PokecordCatcher-master>timeout -1

Press any key to continue ...

ive installed python and i just clicked run and this was what i got

**Comment by bueluke** [comment]
go to windows search bar type cmd open that and type `pip install aiohttp`

**Comment by skondar** [comment]
'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bueluke** [comment]
go to cmd type `python` screenshot what pops up and send her. u either didnt download python or u didnt set it up right

**Comment by skondar** [comment]
![skarmklipp](https://user-images.githubusercontent.com/40062361/41164921-9c3b1978-6b3c-11e8-9f56-4aaaccd51fbe.PNG)

**Comment by bueluke** [comment]
bruh u dont even have python downloaded 😂 https://www.python.org/downloads/ here you go download 3.6.5 and  when python comes up with the setup wizard screenshot it and send it here before u click next or anything because u have to add stuff in the python setup

**Comment by bueluke** [comment]
when the setup for pythons shows at the bottom of the setup click add python to path then click custom installation and click pip and add to enviormental varaiables then install
then next next then go to cmd and type python again and if it shows up 3.6.5 u have it

**Comment by skondar** [comment]
![skarmklipp](https://user-images.githubusercontent.com/40062361/41165501-1c9fe64c-6b3e-11e8-93c0-ea8643e1059c.PNG)
m8 i have downloaded it this is what i got

**Comment by bueluke** [comment]
tf type shit is that what did u download 😂

**Comment by skondar** [comment]
u sent that to me :/

**Comment by bueluke** [comment]
add me on discord so i can help u better Captain Luke #0069

**Comment by skondar** [comment]
i need the # and 4 numbers at the end

**Comment by bueluke** [comment]
#0069

**Comment by skondar** [comment]
add me Skondar#0933

**Comment by bueluke** [comment]
didnt work

**Comment by bueluke** [comment]
kek

**Comment by bueluke** [comment]
Problem fixed! updated to new version 1.0.2 everything works fine :D
