### ISSUE TITLE
Bot closes immediately after I open it

### ISSUE THREAD

**Issue by Vaathys** [xKynn/PokecordCatcher#79]
Hi, 
I'm sorry if a similar issue has been opened before, but I looked and didn't find any.
So, everything is on the title, when I run launcher.exe, the window opens and closes almost immediately. I don't understand, the bot was working fine until this afternoon. I took a screenshot of the message before the window closed. 
PS : If I have to do some process to make it work again, please explain precisely because I'm a noob and I don't know a thing about programming and stuff like that xD
![captura de ecra 245](https://user-images.githubusercontent.com/40214281/41310436-657db888-6e79-11e8-94dc-a9a3ceb5b78b.png)

**Comment by bueluke** [comment]
ill be happy to assist you. https://discord.gg/awu6AM join our support server so i can help you resolve this quicker!

**Comment by bueluke** [comment]
problem fixed on discord. deleted files and re installed new version
