### ISSUE TITLE
Halp?

### ISSUE THREAD

**Issue by Glenta** [xKynn/PokecordCatcher#81]
Everytime I try to run the bat, this happens
 
E:\computer\Downloads\PokecordCatcher-master\PokecordCatcher-master>py -3 launcher.py
'py' is not recognized as an internal or external command,
operable program or batch file.

E:\computer\Downloads\PokecordCatcher-master\PokecordCatcher-master>timeout -1

Press any key to continue ...

**Comment by bueluke** [comment]
do u have python downloaded?

**Comment by Glenta** [comment]
Yes when I type python in command prompt It doesn't have any errors.

**Comment by bueluke** [comment]
go into cmd and type python again
send me a screenshot of what it says

**Comment by Glenta** [comment]
![image](https://user-images.githubusercontent.com/38775826/41391341-102fc8f4-6f68-11e8-9dfb-04ff23f03011.png)

**Comment by bueluke** [comment]
your python is old
delete your python and install 3.6.5 www.python.org/downloads 
when your in the setup there should be a box at the bottom saying add python to path make sure that is clicked and then hit next then install now

**Comment by Glenta** [comment]
Same message :(

**Comment by bueluke** [comment]
ok go into the launcher.py and where it says "py" replace "py" with "python"

**Comment by Glenta** [comment]
Like this right? 
![image](https://user-images.githubusercontent.com/38775826/41391625-a90e05bc-6f69-11e8-88f9-8cb5da8f74b3.png)

**Comment by bueluke** [comment]
nooooooo
that is the fucking file name that has to be launcher.py im talking about inside that the code inside that change the fucking file name back to launcher.py and then right click it and click edit and when it opens up a notepad or something it will say something like py -3 something something etc change the py to python

**Comment by Glenta** [comment]
I like seeing py -3 something something
![image](https://user-images.githubusercontent.com/38775826/41391719-5317d4ac-6f6a-11e8-90d6-42abdcc071e5.png)

**Comment by bueluke** [comment]
shit
i meant run.bat not launcher. right click run then edit change py ty python then save it and run the bot and if i may ask have tyou run the setup.bat and done the config allready?

**Comment by Glenta** [comment]
yes I have ran the setup batch file

**Comment by bueluke** [comment]
ok so change the py to python in the run.bat and then run the thing
hopefully it will wokr if it doesnt ima be here all night 😂

**Comment by Glenta** [comment]
When I run the run file, it automatically closes

**Comment by bueluke** [comment]
tf

**Comment by bueluke** [comment]
idk whats wrong with your thing either there is something fucked with your pc or im not telling u to change the right thing bc i have to admit im really drunk , ima go to sleep g ill help u whenever i wake up

**Comment by Glenta** [comment]
Its 1 am here so... also have school :)

**Comment by bueluke** [comment]
oh its like 12:44am here.. https://discord.gg/aNhxrf join our support server so i can help u tmmr

**Comment by Glenta** [comment]
Say thing it’s 12:47 am here also link doesn’t work :/

**Comment by bueluke** [comment]
https://discord.gg/qRCPGEr

**Comment by Glenta** [comment]
I have downloaded the new files but still have the error above, and I got kicked from discord server...
