### ISSUE TITLE
Error catching Pokemon

### ISSUE THREAD

**Issue by johnsothan** [xKynn/PokecordCatcher#82]
See image https://i.imgur.com/Fhz1zXQ.png

**Comment by xKynn** [comment]
Would be pretty helpful if you could provide what pokemon this happened
with, its alright if you can't I'll look into it

**Comment by johnsothan** [comment]
It happens with alot of pokemons, for example Froslass, Starly, Zigzagoon, Numel, Nidoran(female) and many more.

**Comment by xKynn** [comment]
I'd like to know if its catching anything at all?

**Comment by johnsothan** [comment]
Not really...

**Comment by xKynn** [comment]
Are you sure you're on the latest release? No real updates on the official
pokecord, i dont personally use the bot or play on pokecord at all so I
rely on others for this info

**Comment by johnsothan** [comment]
I am on 1.0.2, but I will try 1.0.3 and see if it works

**Comment by xElfenlied** [comment]
Seems like a lot of ppl got problems with bot since 1.5h

**Comment by johnsothan** [comment]
Nope. not working in 1.0.3 either

**Comment by Faustvii** [comment]
Seems like all the hash values for the images of the pokemons have changed.

**Comment by Ple-ase** [comment]
I can verify that the bot worked properly. than the pokecord bot was down, so he probably updated the images. because it still detects a pokemon spawning, but doesnt know which one.

**Comment by bueluke** [comment]
Join the official support server so we can keep you guys updated https://discord.gg/qRCPGEr

**Comment by Ple-ase** [comment]
invalid @bueluke
