### ISSUE TITLE
Error after downloading latest update

### ISSUE THREAD

**Issue by faponteras** [xKynn/PokecordCatcher#84]
Hi,
I've downloaded the latest version earlier and I'm having errors whenever a pokemon spawns in PokeCord.
![image](https://user-images.githubusercontent.com/30569444/41420580-daf26c48-7005-11e8-83df-f05709cc78ba.png)

**Comment by bueluke** [comment]
pokecord? why are u ising it in pokecord server. and new update is releasing soon

**Comment by faponteras** [comment]
nope. used it in my own server. will wait on the new release.
