### ISSUE TITLE
traceback issue

### ISSUE THREAD

**Issue by Ple-ase** [xKynn/PokecordCatcher#86]
![afbeelding](https://user-images.githubusercontent.com/40267978/41433112-2f3f020e-7018-11e8-8c8c-00012d76e98c.png)

for some reason its searching in lenovo pc??

**Comment by xKynn** [comment]
this is surprising

**Comment by xKynn** [comment]
you're using the release right? i think it mimics paths to create like a fake virtualenv, your only problem is having an old config version

**Comment by xKynn** [comment]
"check_for_updates": false
add this as the last key: val pair in the config
