### ISSUE TITLE
Can't launch after new release.

### ISSUE THREAD

**Issue by erackson** [xKynn/PokecordCatcher#88]
That's the error I get when trying to run the code:
![screen shot 2018-06-14 at 8 22 10 pm](https://user-images.githubusercontent.com/953985/41443030-e191c124-7010-11e8-9c32-6f68a83e2217.png)

That's what I get when running the requirements again:
![screen shot 2018-06-14 at 8 22 51 pm](https://user-images.githubusercontent.com/953985/41443072-19e814ba-7011-11e8-9ed4-a227de86ce8f.png)

I am on Mac.

**Comment by bueluke** [comment]
open cmd and type pip install --upgrade pip

**Comment by erackson** [comment]
I did. That's what I get:
![screen shot 2018-06-14 at 8 34 17 pm](https://user-images.githubusercontent.com/953985/41443293-5f95f1b6-7012-11e8-8627-733267eab138.png)

**Comment by bueluke** [comment]
sudo pip install --upgrade pip

**Comment by erackson** [comment]
Same thing: 
![screen shot 2018-06-14 at 8 39 13 pm](https://user-images.githubusercontent.com/953985/41443415-0fbe679e-7013-11e8-9fae-045b7de72451.png)

**Comment by bueluke** [comment]
idk how to help u man..

**Comment by bueluke** [comment]
if you read the read.me u can find our support server and u can join and we'll try to help u further

**Comment by erackson** [comment]
Thanks.

**Comment by bueluke** [comment]
np

**Comment by xKynn** [comment]
This is a problem with pillow.
try manually installing pillow with this
`pip install 'pillow!=5.1.0'`

**Comment by erackson** [comment]
@xKynn 
I did what you suggested. It seems to be a promising path since the error now is different. xD

![screen shot 2018-06-15 at 8 21 13 am](https://user-images.githubusercontent.com/953985/41465638-5535f5be-7075-11e8-8332-967341df6c3a.png)

**Comment by erackson** [comment]
ulimit -Sn 10000
it's now running.
If anything happens from here I will open another issue. Thanks for helping :D

**Comment by xKynn** [comment]
No worries join the support server if you need more indepth help!
