### ISSUE TITLE
No module named 'PIL'

### ISSUE THREAD

**Issue by xElfenlied** [xKynn/PokecordCatcher#89]
As I try to launch launcher.py
![bots_pokecord](https://user-images.githubusercontent.com/39309657/41443433-1f063248-703d-11e8-869c-d4397cf8ae51.png)

as I try to install the requirements.txt
![_bots_pokecord](https://user-images.githubusercontent.com/39309657/41443456-46801e56-703d-11e8-9f9d-a3a23bea8eaf.png)

the same message pops up as I try to install Pillow myself with `pip install Pillow`

Python3.6 --version = Python 3.6.4
pip --version = pip 10.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

**Comment by bueluke** [comment]
delete the files and reinstall it

**Comment by xElfenlied** [comment]
which files do you mean? 
the catcher files or reinstalling python?

**Comment by xElfenlied** [comment]
thanks for not replying anymore -.-
i guess i just gonna play around till i find the problem.. thanks for the advise that i may reinstall something...
kind regards xElfenlied.

**Comment by xKynn** [comment]
Your linux distro does not have jpeg headers
`sudo apt-get install libjpeg-dev zlib1g-dev`
try this and then install requirements

**Comment by xElfenlied** [comment]
Thank you very much! It worked :)
